// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from "./flatbuffers.ts"
import * as NS11761730870534353095 from "./shared_generated.ts";
/**
 * @enum {number}
 */
export namespace WsGw.proto.Client.Send{
export enum Send{
  NONE= 0,
  GetServiceList= 1,
  WaitService= 2,
  CancelWaitService= 3,
  CallService= 4,
  CancelCallService= 5,
  SubscribeService= 6,
  UnscribeService= 7
}};

/**
 * @enum {number}
 */
export namespace WsGw.proto.Client.Receive{
export enum Receive{
  NONE= 0,
  SyncResult= 1,
  AsyncResult= 2
}};

/**
 * @enum {number}
 */
export namespace WsGw.proto.Client.Receive{
export enum OnlineStatus{
  Offline= 0,
  Online= 1
}};

/**
 * @enum {number}
 */
export namespace WsGw.proto.Client.Receive.Sync{
export enum Sync{
  NONE= 0,
  SimpleResult= 1,
  ServiceList= 2,
  ServiceStatus= 3,
  RequestResult= 4
}};

/**
 * @enum {number}
 */
export namespace WsGw.proto.Client.Receive.Async{
export enum Async{
  NONE= 0,
  WaitResult= 1,
  CallResponse= 2,
  Event= 3
}};

/**
 * @enum {number}
 */
export namespace WsGw.proto.Client.Receive.Async.Call{
export enum CallResponsePayload{
  NONE= 0,
  CallSuccess= 1,
  CallException= 2
}};

/**
 * @constructor
 */
export namespace WsGw.proto.Client{
export class Handshake {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Handshake
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Handshake {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Handshake= obj
 * @returns Handshake
 */
static getRootAsHandshake(bb:flatbuffers.ByteBuffer, obj?:Handshake):Handshake {
  return (obj || new Handshake).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
magic():string|null
magic(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
magic(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns number
 */
version():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startHandshake(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset magicOffset
 */
static addMagic(builder:flatbuffers.Builder, magicOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, magicOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number version
 */
static addVersion(builder:flatbuffers.Builder, version:number) {
  builder.addFieldInt32(1, version, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endHandshake(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createHandshake(builder:flatbuffers.Builder, magicOffset:flatbuffers.Offset, version:number):flatbuffers.Offset {
  Handshake.startHandshake(builder);
  Handshake.addMagic(builder, magicOffset);
  Handshake.addVersion(builder, version);
  return Handshake.endHandshake(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client{
export class HandshakeResponse {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns HandshakeResponse
 */
__init(i:number, bb:flatbuffers.ByteBuffer):HandshakeResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param HandshakeResponse= obj
 * @returns HandshakeResponse
 */
static getRootAsHandshakeResponse(bb:flatbuffers.ByteBuffer, obj?:HandshakeResponse):HandshakeResponse {
  return (obj || new HandshakeResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
magic():string|null
magic(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
magic(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startHandshakeResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset magicOffset
 */
static addMagic(builder:flatbuffers.Builder, magicOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, magicOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endHandshakeResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createHandshakeResponse(builder:flatbuffers.Builder, magicOffset:flatbuffers.Offset):flatbuffers.Offset {
  HandshakeResponse.startHandshakeResponse(builder);
  HandshakeResponse.addMagic(builder, magicOffset);
  return HandshakeResponse.endHandshakeResponse(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Send{
export class SendPacket {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns SendPacket
 */
__init(i:number, bb:flatbuffers.ByteBuffer):SendPacket {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param SendPacket= obj
 * @returns SendPacket
 */
static getRootAsSendPacket(bb:flatbuffers.ByteBuffer, obj?:SendPacket):SendPacket {
  return (obj || new SendPacket).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns WsGw.proto.Client.Send.Send
 */
sendType():WsGw.proto.Client.Send.Send {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : WsGw.proto.Client.Send.Send.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
send<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startSendPacket(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param WsGw.proto.Client.Send.Send sendType
 */
static addSendType(builder:flatbuffers.Builder, sendType:WsGw.proto.Client.Send.Send) {
  builder.addFieldInt8(0, sendType, WsGw.proto.Client.Send.Send.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset sendOffset
 */
static addSend(builder:flatbuffers.Builder, sendOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, sendOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endSendPacket(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createSendPacket(builder:flatbuffers.Builder, sendType:WsGw.proto.Client.Send.Send, sendOffset:flatbuffers.Offset):flatbuffers.Offset {
  SendPacket.startSendPacket(builder);
  SendPacket.addSendType(builder, sendType);
  SendPacket.addSend(builder, sendOffset);
  return SendPacket.endSendPacket(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Send{
export class GetServiceList {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns GetServiceList
 */
__init(i:number, bb:flatbuffers.ByteBuffer):GetServiceList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param GetServiceList= obj
 * @returns GetServiceList
 */
static getRootAsGetServiceList(bb:flatbuffers.ByteBuffer, obj?:GetServiceList):GetServiceList {
  return (obj || new GetServiceList).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Builder builder
 */
static startGetServiceList(builder:flatbuffers.Builder) {
  builder.startObject(0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endGetServiceList(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createGetServiceList(builder:flatbuffers.Builder):flatbuffers.Offset {
  GetServiceList.startGetServiceList(builder);
  return GetServiceList.endGetServiceList(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Send{
export class WaitService {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns WaitService
 */
__init(i:number, bb:flatbuffers.ByteBuffer):WaitService {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param WaitService= obj
 * @returns WaitService
 */
static getRootAsWaitService(bb:flatbuffers.ByteBuffer, obj?:WaitService):WaitService {
  return (obj || new WaitService).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startWaitService(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endWaitService(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createWaitService(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset):flatbuffers.Offset {
  WaitService.startWaitService(builder);
  WaitService.addName(builder, nameOffset);
  return WaitService.endWaitService(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Send{
export class CancelWaitService {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns CancelWaitService
 */
__init(i:number, bb:flatbuffers.ByteBuffer):CancelWaitService {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param CancelWaitService= obj
 * @returns CancelWaitService
 */
static getRootAsCancelWaitService(bb:flatbuffers.ByteBuffer, obj?:CancelWaitService):CancelWaitService {
  return (obj || new CancelWaitService).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startCancelWaitService(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endCancelWaitService(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createCancelWaitService(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset):flatbuffers.Offset {
  CancelWaitService.startCancelWaitService(builder);
  CancelWaitService.addName(builder, nameOffset);
  return CancelWaitService.endCancelWaitService(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Send{
export class CallService {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns CallService
 */
__init(i:number, bb:flatbuffers.ByteBuffer):CallService {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param CallService= obj
 * @returns CallService
 */
static getRootAsCallService(bb:flatbuffers.ByteBuffer, obj?:CallService):CallService {
  return (obj || new CallService).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param number index
 * @returns number
 */
payload(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
payloadLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
payloadArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startCallService(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset keyOffset
 */
static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, keyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset payloadOffset
 */
static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, payloadOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createPayloadVector(builder:flatbuffers.Builder, data:number[] | Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endCallService(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createCallService(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, keyOffset:flatbuffers.Offset, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  CallService.startCallService(builder);
  CallService.addName(builder, nameOffset);
  CallService.addKey(builder, keyOffset);
  CallService.addPayload(builder, payloadOffset);
  return CallService.endCallService(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Send{
export class CancelCallService {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns CancelCallService
 */
__init(i:number, bb:flatbuffers.ByteBuffer):CancelCallService {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param CancelCallService= obj
 * @returns CancelCallService
 */
static getRootAsCancelCallService(bb:flatbuffers.ByteBuffer, obj?:CancelCallService):CancelCallService {
  return (obj || new CancelCallService).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns number
 */
id():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startCancelCallService(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number id
 */
static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(1, id, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endCancelCallService(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createCancelCallService(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, id:number):flatbuffers.Offset {
  CancelCallService.startCancelCallService(builder);
  CancelCallService.addName(builder, nameOffset);
  CancelCallService.addId(builder, id);
  return CancelCallService.endCancelCallService(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Send{
export class SubscribeService {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns SubscribeService
 */
__init(i:number, bb:flatbuffers.ByteBuffer):SubscribeService {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param SubscribeService= obj
 * @returns SubscribeService
 */
static getRootAsSubscribeService(bb:flatbuffers.ByteBuffer, obj?:SubscribeService):SubscribeService {
  return (obj || new SubscribeService).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startSubscribeService(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset keyOffset
 */
static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, keyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endSubscribeService(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createSubscribeService(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, keyOffset:flatbuffers.Offset):flatbuffers.Offset {
  SubscribeService.startSubscribeService(builder);
  SubscribeService.addName(builder, nameOffset);
  SubscribeService.addKey(builder, keyOffset);
  return SubscribeService.endSubscribeService(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Send{
export class UnscribeService {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns UnscribeService
 */
__init(i:number, bb:flatbuffers.ByteBuffer):UnscribeService {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param UnscribeService= obj
 * @returns UnscribeService
 */
static getRootAsUnscribeService(bb:flatbuffers.ByteBuffer, obj?:UnscribeService):UnscribeService {
  return (obj || new UnscribeService).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startUnscribeService(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset keyOffset
 */
static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, keyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endUnscribeService(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createUnscribeService(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, keyOffset:flatbuffers.Offset):flatbuffers.Offset {
  UnscribeService.startUnscribeService(builder);
  UnscribeService.addName(builder, nameOffset);
  UnscribeService.addKey(builder, keyOffset);
  return UnscribeService.endUnscribeService(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Receive{
export class ReceivePacket {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ReceivePacket
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ReceivePacket {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ReceivePacket= obj
 * @returns ReceivePacket
 */
static getRootAsReceivePacket(bb:flatbuffers.ByteBuffer, obj?:ReceivePacket):ReceivePacket {
  return (obj || new ReceivePacket).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns WsGw.proto.Client.Receive.Receive
 */
receiveType():WsGw.proto.Client.Receive.Receive {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : WsGw.proto.Client.Receive.Receive.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
receive<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startReceivePacket(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param WsGw.proto.Client.Receive.Receive receiveType
 */
static addReceiveType(builder:flatbuffers.Builder, receiveType:WsGw.proto.Client.Receive.Receive) {
  builder.addFieldInt8(0, receiveType, WsGw.proto.Client.Receive.Receive.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset receiveOffset
 */
static addReceive(builder:flatbuffers.Builder, receiveOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, receiveOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endReceivePacket(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createReceivePacket(builder:flatbuffers.Builder, receiveType:WsGw.proto.Client.Receive.Receive, receiveOffset:flatbuffers.Offset):flatbuffers.Offset {
  ReceivePacket.startReceivePacket(builder);
  ReceivePacket.addReceiveType(builder, receiveType);
  ReceivePacket.addReceive(builder, receiveOffset);
  return ReceivePacket.endReceivePacket(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Receive.Sync{
export class SimpleResult {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns SimpleResult
 */
__init(i:number, bb:flatbuffers.ByteBuffer):SimpleResult {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param SimpleResult= obj
 * @returns SimpleResult
 */
static getRootAsSimpleResult(bb:flatbuffers.ByteBuffer, obj?:SimpleResult):SimpleResult {
  return (obj || new SimpleResult).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns boolean
 */
ok():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param flatbuffers.Builder builder
 */
static startSimpleResult(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean ok
 */
static addOk(builder:flatbuffers.Builder, ok:boolean) {
  builder.addFieldInt8(0, +ok, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endSimpleResult(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createSimpleResult(builder:flatbuffers.Builder, ok:boolean):flatbuffers.Offset {
  SimpleResult.startSimpleResult(builder);
  SimpleResult.addOk(builder, ok);
  return SimpleResult.endSimpleResult(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Receive.Sync{
export class ServiceDesc {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ServiceDesc
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ServiceDesc {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ServiceDesc= obj
 * @returns ServiceDesc
 */
static getRootAsServiceDesc(bb:flatbuffers.ByteBuffer, obj?:ServiceDesc):ServiceDesc {
  return (obj || new ServiceDesc).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
type():string|null
type(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
type(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
version():string|null
version(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
version(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startServiceDesc(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset typeOffset
 */
static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, typeOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset versionOffset
 */
static addVersion(builder:flatbuffers.Builder, versionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, versionOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endServiceDesc(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createServiceDesc(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, typeOffset:flatbuffers.Offset, versionOffset:flatbuffers.Offset):flatbuffers.Offset {
  ServiceDesc.startServiceDesc(builder);
  ServiceDesc.addName(builder, nameOffset);
  ServiceDesc.addType(builder, typeOffset);
  ServiceDesc.addVersion(builder, versionOffset);
  return ServiceDesc.endServiceDesc(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Receive.Sync{
export class ServiceList {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ServiceList
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ServiceList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ServiceList= obj
 * @returns ServiceList
 */
static getRootAsServiceList(bb:flatbuffers.ByteBuffer, obj?:ServiceList):ServiceList {
  return (obj || new ServiceList).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @param WsGw.proto.Client.Receive.Sync.ServiceDesc= obj
 * @returns WsGw.proto.Client.Receive.Sync.ServiceDesc
 */
list(index: number, obj?:WsGw.proto.Client.Receive.Sync.ServiceDesc):WsGw.proto.Client.Receive.Sync.ServiceDesc|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new WsGw.proto.Client.Receive.Sync.ServiceDesc).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
listLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startServiceList(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset listOffset
 */
static addList(builder:flatbuffers.Builder, listOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, listOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endServiceList(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createServiceList(builder:flatbuffers.Builder, listOffset:flatbuffers.Offset):flatbuffers.Offset {
  ServiceList.startServiceList(builder);
  ServiceList.addList(builder, listOffset);
  return ServiceList.endServiceList(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Receive.Sync{
export class ServiceStatus {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ServiceStatus
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ServiceStatus {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ServiceStatus= obj
 * @returns ServiceStatus
 */
static getRootAsServiceStatus(bb:flatbuffers.ByteBuffer, obj?:ServiceStatus):ServiceStatus {
  return (obj || new ServiceStatus).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns WsGw.proto.Client.Receive.OnlineStatus
 */
status():WsGw.proto.Client.Receive.OnlineStatus {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : WsGw.proto.Client.Receive.OnlineStatus.Offline;
};

/**
 * @param flatbuffers.Builder builder
 */
static startServiceStatus(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param WsGw.proto.Client.Receive.OnlineStatus status
 */
static addStatus(builder:flatbuffers.Builder, status:WsGw.proto.Client.Receive.OnlineStatus) {
  builder.addFieldInt8(0, status, WsGw.proto.Client.Receive.OnlineStatus.Offline);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endServiceStatus(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createServiceStatus(builder:flatbuffers.Builder, status:WsGw.proto.Client.Receive.OnlineStatus):flatbuffers.Offset {
  ServiceStatus.startServiceStatus(builder);
  ServiceStatus.addStatus(builder, status);
  return ServiceStatus.endServiceStatus(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Receive.Sync{
export class RequestResult {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns RequestResult
 */
__init(i:number, bb:flatbuffers.ByteBuffer):RequestResult {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param RequestResult= obj
 * @returns RequestResult
 */
static getRootAsRequestResult(bb:flatbuffers.ByteBuffer, obj?:RequestResult):RequestResult {
  return (obj || new RequestResult).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
id():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startRequestResult(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param number id
 */
static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endRequestResult(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createRequestResult(builder:flatbuffers.Builder, id:number):flatbuffers.Offset {
  RequestResult.startRequestResult(builder);
  RequestResult.addId(builder, id);
  return RequestResult.endRequestResult(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Receive.Sync{
export class SyncResult {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns SyncResult
 */
__init(i:number, bb:flatbuffers.ByteBuffer):SyncResult {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param SyncResult= obj
 * @returns SyncResult
 */
static getRootAsSyncResult(bb:flatbuffers.ByteBuffer, obj?:SyncResult):SyncResult {
  return (obj || new SyncResult).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns WsGw.proto.Client.Receive.Sync.Sync
 */
syncType():WsGw.proto.Client.Receive.Sync.Sync {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : WsGw.proto.Client.Receive.Sync.Sync.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
sync<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startSyncResult(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param WsGw.proto.Client.Receive.Sync.Sync syncType
 */
static addSyncType(builder:flatbuffers.Builder, syncType:WsGw.proto.Client.Receive.Sync.Sync) {
  builder.addFieldInt8(0, syncType, WsGw.proto.Client.Receive.Sync.Sync.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset syncOffset
 */
static addSync(builder:flatbuffers.Builder, syncOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, syncOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endSyncResult(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createSyncResult(builder:flatbuffers.Builder, syncType:WsGw.proto.Client.Receive.Sync.Sync, syncOffset:flatbuffers.Offset):flatbuffers.Offset {
  SyncResult.startSyncResult(builder);
  SyncResult.addSyncType(builder, syncType);
  SyncResult.addSync(builder, syncOffset);
  return SyncResult.endSyncResult(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Receive.Async{
export class AsyncResult {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns AsyncResult
 */
__init(i:number, bb:flatbuffers.ByteBuffer):AsyncResult {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param AsyncResult= obj
 * @returns AsyncResult
 */
static getRootAsAsyncResult(bb:flatbuffers.ByteBuffer, obj?:AsyncResult):AsyncResult {
  return (obj || new AsyncResult).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns WsGw.proto.Client.Receive.Async.Async
 */
asyncType():WsGw.proto.Client.Receive.Async.Async {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : WsGw.proto.Client.Receive.Async.Async.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
async<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startAsyncResult(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param WsGw.proto.Client.Receive.Async.Async asyncType
 */
static addAsyncType(builder:flatbuffers.Builder, asyncType:WsGw.proto.Client.Receive.Async.Async) {
  builder.addFieldInt8(0, asyncType, WsGw.proto.Client.Receive.Async.Async.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset asyncOffset
 */
static addAsync(builder:flatbuffers.Builder, asyncOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, asyncOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endAsyncResult(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createAsyncResult(builder:flatbuffers.Builder, asyncType:WsGw.proto.Client.Receive.Async.Async, asyncOffset:flatbuffers.Offset):flatbuffers.Offset {
  AsyncResult.startAsyncResult(builder);
  AsyncResult.addAsyncType(builder, asyncType);
  AsyncResult.addAsync(builder, asyncOffset);
  return AsyncResult.endAsyncResult(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Receive.Async{
export class WaitResult {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns WaitResult
 */
__init(i:number, bb:flatbuffers.ByteBuffer):WaitResult {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param WaitResult= obj
 * @returns WaitResult
 */
static getRootAsWaitResult(bb:flatbuffers.ByteBuffer, obj?:WaitResult):WaitResult {
  return (obj || new WaitResult).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns WsGw.proto.Client.Receive.OnlineStatus
 */
status():WsGw.proto.Client.Receive.OnlineStatus {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : WsGw.proto.Client.Receive.OnlineStatus.Offline;
};

/**
 * @param flatbuffers.Builder builder
 */
static startWaitResult(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param WsGw.proto.Client.Receive.OnlineStatus status
 */
static addStatus(builder:flatbuffers.Builder, status:WsGw.proto.Client.Receive.OnlineStatus) {
  builder.addFieldInt8(1, status, WsGw.proto.Client.Receive.OnlineStatus.Offline);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endWaitResult(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createWaitResult(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, status:WsGw.proto.Client.Receive.OnlineStatus):flatbuffers.Offset {
  WaitResult.startWaitResult(builder);
  WaitResult.addName(builder, nameOffset);
  WaitResult.addStatus(builder, status);
  return WaitResult.endWaitResult(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Receive.Async.Call{
export class CallResponse {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns CallResponse
 */
__init(i:number, bb:flatbuffers.ByteBuffer):CallResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param CallResponse= obj
 * @returns CallResponse
 */
static getRootAsCallResponse(bb:flatbuffers.ByteBuffer, obj?:CallResponse):CallResponse {
  return (obj || new CallResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns number
 */
id():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @returns WsGw.proto.Client.Receive.Async.Call.CallResponsePayload
 */
payloadType():WsGw.proto.Client.Receive.Async.Call.CallResponsePayload {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : WsGw.proto.Client.Receive.Async.Call.CallResponsePayload.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
payload<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startCallResponse(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number id
 */
static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(1, id, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param WsGw.proto.Client.Receive.Async.Call.CallResponsePayload payloadType
 */
static addPayloadType(builder:flatbuffers.Builder, payloadType:WsGw.proto.Client.Receive.Async.Call.CallResponsePayload) {
  builder.addFieldInt8(2, payloadType, WsGw.proto.Client.Receive.Async.Call.CallResponsePayload.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset payloadOffset
 */
static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, payloadOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endCallResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createCallResponse(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, id:number, payloadType:WsGw.proto.Client.Receive.Async.Call.CallResponsePayload, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  CallResponse.startCallResponse(builder);
  CallResponse.addName(builder, nameOffset);
  CallResponse.addId(builder, id);
  CallResponse.addPayloadType(builder, payloadType);
  CallResponse.addPayload(builder, payloadOffset);
  return CallResponse.endCallResponse(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Receive.Async.Call{
export class CallSuccess {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns CallSuccess
 */
__init(i:number, bb:flatbuffers.ByteBuffer):CallSuccess {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param CallSuccess= obj
 * @returns CallSuccess
 */
static getRootAsCallSuccess(bb:flatbuffers.ByteBuffer, obj?:CallSuccess):CallSuccess {
  return (obj || new CallSuccess).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @returns number
 */
payload(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
payloadLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
payloadArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startCallSuccess(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset payloadOffset
 */
static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, payloadOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createPayloadVector(builder:flatbuffers.Builder, data:number[] | Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endCallSuccess(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createCallSuccess(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  CallSuccess.startCallSuccess(builder);
  CallSuccess.addPayload(builder, payloadOffset);
  return CallSuccess.endCallSuccess(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Receive.Async.Call{
export class CallException {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns CallException
 */
__init(i:number, bb:flatbuffers.ByteBuffer):CallException {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param CallException= obj
 * @returns CallException
 */
static getRootAsCallException(bb:flatbuffers.ByteBuffer, obj?:CallException):CallException {
  return (obj || new CallException).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param WsGw.proto.ExceptionInfo= obj
 * @returns WsGw.proto.ExceptionInfo|null
 */
info(obj?:NS11761730870534353095.WsGw.proto.ExceptionInfo):NS11761730870534353095.WsGw.proto.ExceptionInfo|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NS11761730870534353095.WsGw.proto.ExceptionInfo).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startCallException(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset infoOffset
 */
static addInfo(builder:flatbuffers.Builder, infoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, infoOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endCallException(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createCallException(builder:flatbuffers.Builder, infoOffset:flatbuffers.Offset):flatbuffers.Offset {
  CallException.startCallException(builder);
  CallException.addInfo(builder, infoOffset);
  return CallException.endCallException(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Receive.Async.Event{
export class EventPayload {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns EventPayload
 */
__init(i:number, bb:flatbuffers.ByteBuffer):EventPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param EventPayload= obj
 * @returns EventPayload
 */
static getRootAsEventPayload(bb:flatbuffers.ByteBuffer, obj?:EventPayload):EventPayload {
  return (obj || new EventPayload).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @returns number
 */
payload(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
payloadLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
payloadArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startEventPayload(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset payloadOffset
 */
static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, payloadOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createPayloadVector(builder:flatbuffers.Builder, data:number[] | Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endEventPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createEventPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  EventPayload.startEventPayload(builder);
  EventPayload.addPayload(builder, payloadOffset);
  return EventPayload.endEventPayload(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Client.Receive.Async.Event{
export class Event {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Event
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Event {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Event= obj
 * @returns Event
 */
static getRootAsEvent(bb:flatbuffers.ByteBuffer, obj?:Event):Event {
  return (obj || new Event).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param WsGw.proto.Client.Receive.Async.Event.EventPayload= obj
 * @returns WsGw.proto.Client.Receive.Async.Event.EventPayload|null
 */
payload(obj?:WsGw.proto.Client.Receive.Async.Event.EventPayload):WsGw.proto.Client.Receive.Async.Event.EventPayload|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new WsGw.proto.Client.Receive.Async.Event.EventPayload).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startEvent(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset keyOffset
 */
static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, keyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset payloadOffset
 */
static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, payloadOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createEvent(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, keyOffset:flatbuffers.Offset, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  Event.startEvent(builder);
  Event.addName(builder, nameOffset);
  Event.addKey(builder, keyOffset);
  Event.addPayload(builder, payloadOffset);
  return Event.endEvent(builder);
}
}
}
