// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from "./flatbuffers.ts"
import * as NS11761730870534353095 from "./shared_generated.ts";
/**
 * @enum {number}
 */
export namespace WsGw.proto.Service.Send{
export enum Send{
  NONE= 0,
  Response= 1,
  Exception= 2,
  Broadcast= 3
}};

/**
 * @enum {number}
 */
export namespace WsGw.proto.Service.Receive{
export enum Receive{
  NONE= 0,
  Request= 1,
  CancelRequest= 2
}};

/**
 * @constructor
 */
export namespace WsGw.proto.Service{
export class Handshake {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Handshake
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Handshake {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Handshake= obj
 * @returns Handshake
 */
static getRootAsHandshake(bb:flatbuffers.ByteBuffer, obj?:Handshake):Handshake {
  return (obj || new Handshake).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
magic():string|null
magic(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
magic(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns number
 */
version():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
type():string|null
type(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
type(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
srvver():string|null
srvver(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
srvver(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startHandshake(builder:flatbuffers.Builder) {
  builder.startObject(5);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset magicOffset
 */
static addMagic(builder:flatbuffers.Builder, magicOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, magicOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number version
 */
static addVersion(builder:flatbuffers.Builder, version:number) {
  builder.addFieldInt32(1, version, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset typeOffset
 */
static addType(builder:flatbuffers.Builder, typeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, typeOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset srvverOffset
 */
static addSrvver(builder:flatbuffers.Builder, srvverOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, srvverOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endHandshake(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createHandshake(builder:flatbuffers.Builder, magicOffset:flatbuffers.Offset, version:number, nameOffset:flatbuffers.Offset, typeOffset:flatbuffers.Offset, srvverOffset:flatbuffers.Offset):flatbuffers.Offset {
  Handshake.startHandshake(builder);
  Handshake.addMagic(builder, magicOffset);
  Handshake.addVersion(builder, version);
  Handshake.addName(builder, nameOffset);
  Handshake.addType(builder, typeOffset);
  Handshake.addSrvver(builder, srvverOffset);
  return Handshake.endHandshake(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Service{
export class HandshakeResponse {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns HandshakeResponse
 */
__init(i:number, bb:flatbuffers.ByteBuffer):HandshakeResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param HandshakeResponse= obj
 * @returns HandshakeResponse
 */
static getRootAsHandshakeResponse(bb:flatbuffers.ByteBuffer, obj?:HandshakeResponse):HandshakeResponse {
  return (obj || new HandshakeResponse).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
magic():string|null
magic(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
magic(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startHandshakeResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset magicOffset
 */
static addMagic(builder:flatbuffers.Builder, magicOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, magicOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endHandshakeResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createHandshakeResponse(builder:flatbuffers.Builder, magicOffset:flatbuffers.Offset):flatbuffers.Offset {
  HandshakeResponse.startHandshakeResponse(builder);
  HandshakeResponse.addMagic(builder, magicOffset);
  return HandshakeResponse.endHandshakeResponse(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Service.Send{
export class SendPacket {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns SendPacket
 */
__init(i:number, bb:flatbuffers.ByteBuffer):SendPacket {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param SendPacket= obj
 * @returns SendPacket
 */
static getRootAsSendPacket(bb:flatbuffers.ByteBuffer, obj?:SendPacket):SendPacket {
  return (obj || new SendPacket).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns WsGw.proto.Service.Send.Send
 */
packetType():WsGw.proto.Service.Send.Send {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : WsGw.proto.Service.Send.Send.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
packet<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startSendPacket(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param WsGw.proto.Service.Send.Send packetType
 */
static addPacketType(builder:flatbuffers.Builder, packetType:WsGw.proto.Service.Send.Send) {
  builder.addFieldInt8(0, packetType, WsGw.proto.Service.Send.Send.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset packetOffset
 */
static addPacket(builder:flatbuffers.Builder, packetOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, packetOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endSendPacket(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createSendPacket(builder:flatbuffers.Builder, packetType:WsGw.proto.Service.Send.Send, packetOffset:flatbuffers.Offset):flatbuffers.Offset {
  SendPacket.startSendPacket(builder);
  SendPacket.addPacketType(builder, packetType);
  SendPacket.addPacket(builder, packetOffset);
  return SendPacket.endSendPacket(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Service.Send{
export class Response {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Response
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Response {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Response= obj
 * @returns Response
 */
static getRootAsResponse(bb:flatbuffers.ByteBuffer, obj?:Response):Response {
  return (obj || new Response).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
id():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param number index
 * @returns number
 */
payload(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
payloadLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
payloadArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param number id
 */
static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset payloadOffset
 */
static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, payloadOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createPayloadVector(builder:flatbuffers.Builder, data:number[] | Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createResponse(builder:flatbuffers.Builder, id:number, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  Response.startResponse(builder);
  Response.addId(builder, id);
  Response.addPayload(builder, payloadOffset);
  return Response.endResponse(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Service.Send{
export class Exception {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Exception
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Exception {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Exception= obj
 * @returns Exception
 */
static getRootAsException(bb:flatbuffers.ByteBuffer, obj?:Exception):Exception {
  return (obj || new Exception).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
id():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param WsGw.proto.ExceptionInfo= obj
 * @returns WsGw.proto.ExceptionInfo|null
 */
info(obj?:NS11761730870534353095.WsGw.proto.ExceptionInfo):NS11761730870534353095.WsGw.proto.ExceptionInfo|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new NS11761730870534353095.WsGw.proto.ExceptionInfo).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startException(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param number id
 */
static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset infoOffset
 */
static addInfo(builder:flatbuffers.Builder, infoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, infoOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endException(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createException(builder:flatbuffers.Builder, id:number, infoOffset:flatbuffers.Offset):flatbuffers.Offset {
  Exception.startException(builder);
  Exception.addId(builder, id);
  Exception.addInfo(builder, infoOffset);
  return Exception.endException(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Service.Send{
export class Broadcast {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Broadcast
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Broadcast {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Broadcast= obj
 * @returns Broadcast
 */
static getRootAsBroadcast(bb:flatbuffers.ByteBuffer, obj?:Broadcast):Broadcast {
  return (obj || new Broadcast).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param number index
 * @returns number
 */
payload(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
payloadLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
payloadArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startBroadcast(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset keyOffset
 */
static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset payloadOffset
 */
static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, payloadOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createPayloadVector(builder:flatbuffers.Builder, data:number[] | Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endBroadcast(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createBroadcast(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  Broadcast.startBroadcast(builder);
  Broadcast.addKey(builder, keyOffset);
  Broadcast.addPayload(builder, payloadOffset);
  return Broadcast.endBroadcast(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Service.Receive{
export class ReceivePacket {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ReceivePacket
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ReceivePacket {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ReceivePacket= obj
 * @returns ReceivePacket
 */
static getRootAsReceivePacket(bb:flatbuffers.ByteBuffer, obj?:ReceivePacket):ReceivePacket {
  return (obj || new ReceivePacket).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns WsGw.proto.Service.Receive.Receive
 */
packetType():WsGw.proto.Service.Receive.Receive {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : WsGw.proto.Service.Receive.Receive.NONE;
};

/**
 * @param flatbuffers.Table obj
 * @returns ?flatbuffers.Table
 */
packet<T extends flatbuffers.Table>(obj:T):T|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startReceivePacket(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param WsGw.proto.Service.Receive.Receive packetType
 */
static addPacketType(builder:flatbuffers.Builder, packetType:WsGw.proto.Service.Receive.Receive) {
  builder.addFieldInt8(0, packetType, WsGw.proto.Service.Receive.Receive.NONE);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset packetOffset
 */
static addPacket(builder:flatbuffers.Builder, packetOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, packetOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endReceivePacket(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createReceivePacket(builder:flatbuffers.Builder, packetType:WsGw.proto.Service.Receive.Receive, packetOffset:flatbuffers.Offset):flatbuffers.Offset {
  ReceivePacket.startReceivePacket(builder);
  ReceivePacket.addPacketType(builder, packetType);
  ReceivePacket.addPacket(builder, packetOffset);
  return ReceivePacket.endReceivePacket(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Service.Receive{
export class Request {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Request
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Request {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Request= obj
 * @returns Request
 */
static getRootAsRequest(bb:flatbuffers.ByteBuffer, obj?:Request):Request {
  return (obj || new Request).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns number
 */
id():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param number index
 * @returns number
 */
payload(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
payloadLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
payloadArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset keyOffset
 */
static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number id
 */
static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(1, id, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset payloadOffset
 */
static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, payloadOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createPayloadVector(builder:flatbuffers.Builder, data:number[] | Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createRequest(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset, id:number, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  Request.startRequest(builder);
  Request.addKey(builder, keyOffset);
  Request.addId(builder, id);
  Request.addPayload(builder, payloadOffset);
  return Request.endRequest(builder);
}
}
}
/**
 * @constructor
 */
export namespace WsGw.proto.Service.Receive{
export class CancelRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns CancelRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):CancelRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param CancelRequest= obj
 * @returns CancelRequest
 */
static getRootAsCancelRequest(bb:flatbuffers.ByteBuffer, obj?:CancelRequest):CancelRequest {
  return (obj || new CancelRequest).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
id():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Builder builder
 */
static startCancelRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
};

/**
 * @param flatbuffers.Builder builder
 * @param number id
 */
static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(0, id, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endCancelRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createCancelRequest(builder:flatbuffers.Builder, id:number):flatbuffers.Offset {
  CancelRequest.startCancelRequest(builder);
  CancelRequest.addId(builder, id);
  return CancelRequest.endCancelRequest(builder);
}
}
}
